version: '3.7'

services:
  db:
    image: postgres:11.5
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: redis:4.0.14
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
