version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout

      # Yarn
      ## restore yarn cache
      - restore_cache:
          key: yarn {{ checksum "yarn.lock" }}

      ## yarn install dependencies
      - run: yarn install --frozen-lockfile

      ## store yarn cache
      - save_cache:
          key: yarn {{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Build
      - run: yarn build
