version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/postgres:9.4.12-alpine
      - image: redis:2.8.6

    environment:
      PGUSER: ubuntu
      RAILS_ENV: test
      RACK_ENV: test
      GENERATE_SOURCEMAP: false

    steps:
      # Checkout the source code
      - checkout
      - run: git submodule update --init

      # Restore bundle cache
      - type: cache-restore
        key: Gemfile-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --with ci --without production --without development --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: Gemfile-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Restore yarn cache
      - restore_cache:
          key: |
            yarn
            {{ checksum "yarn.lock" }}
            {{ checksum "client/yarn.lock" }}
            {{ checksum "clients/admin_next/yarn.lock" }}
            {{ checksum "clients/player_app/yarn.lock" }}

      # Yarn install dependencies
      - run: yarn install

      # Store yarn cache
      - save_cache:
          key: |
            yarn
            {{ checksum "yarn.lock" }}
            {{ checksum "client/yarn.lock" }}
            {{ checksum "clients/admin_next/yarn.lock" }}
            {{ checksum "clients/player_app/yarn.lock" }}
          paths:
            - ./node_modules
            - ./client/node_modules
            - ./clients/player_app/node_modules
            - ./clients/admin_next/node_modules

      # Generate checksum for assets
      - type: shell
        command: |
          find app/assets/* -type f 2>/dev/null -exec md5sum {} \; > assets-checksum.txt

      # Restore assets cache
      - restore_cache:
          key: |
            assets
            {{ checksum "assets-checksum.txt" }}
            {{ checksum "Gemfile.lock" }}
            {{ checksum "client/yarn.lock" }}

      # Compile assets
      - run: bundle exec rake assets:precompile

      # Store assets cache
      - save_cache:
          key: |
            assets
            {{ checksum "assets-checksum.txt" }}
            {{ checksum "Gemfile.lock" }}
            {{ checksum "client/yarn.lock" }}
          paths:
            - public/assets
            - public/webpack
            - tmp/cache/assets

      # Build admin_next
      - run: cd clients/admin_next && npm run build
      - run: cd clients/admin_next && yarn type-check

      # Generate checksum for player_app
      - type: shell
        command: |
          git submodule status > player_app-checksum.txt

      # Restore player_app cache
      - restore_cache:
          key: player_app-{{ checksum "player_app-checksum.txt" }}

      # Build player_app
      - run: cd clients/player_app && yarn build

      # Store player_app cache
      - save_cache:
          key: player_app-{{ checksum "player_app-checksum.txt" }}
          paths:
            - clients/player_app/build

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run tests
      - run: bundle exec rake ci:all

      # Store Artifacts
      - store_artifacts:
          path: ~/project/tmp/coverage
          destination: coverage

      - store_artifacts:
          path: ~/project/tmp/capybara
          destination: capybara

      - store_artifacts:
          path: /home/circleci/.npm/_logs
          destination: npm
