version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/postgres:11.5
      - image: redis:4.0.14

    environment:
      PGUSER: ubuntu
      RACK_ENV: test
      RAILS_ENV: test
      REACT_APP_RAILS_ENV: test
      GENERATE_SOURCEMAP: false

    steps:
      # Checkout the source code
      - checkout

      # Bundler
      ## restore bundle cache
      - restore_cache:
          key: Gemfile-{{ checksum "Gemfile.lock" }}

      ## bundle install dependencies
      - run: bundle install --with ci --without production --without development --path .bundle

      ## store bundle cache
      - save_cache:
          key: Gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

      # Yarn
      ## restore yarn cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      ## yarn install dependencies
      - run: yarn install

      ## store yarn cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn


      # Admin
      ## generate checksum for admin
      - type: shell
        command: ./.circleci/admin_checksum.sh > admin-checksum.txt

      ## restore admin cache
      - restore_cache:
          key: admin-{{ checksum "admin-checksum.txt" }}

      ## build admin
      - run:
          working_directory: clients/admin
          command: if [ ! -d "build" ]; then yarn build; fi

      ## store admin cache
      - save_cache:
          key: admin-{{ checksum "yarn.lock" }}-{{ checksum "app/graphql/schema.graphql" }}-{{ checksum "admin-checksum.txt" }}
          paths:
            - clients/admin/src/generated.ts
            - clients/admin/types/generated.d.ts
            - clients/admin/build

      ## typecheck the admin
      - run:
          working_directory: clients/admin
          command: yarn type-check


      # Player App
      ## generate checksum for player_app
      - type: shell
        command: ./.circleci/player_app_checksum.sh > player_app-checksum.txt

      ## restore player_app cache
      - restore_cache:
          key: player_app-{{ checksum "yarn.lock" }}-{{ checksum "app/graphql/schema.graphql" }}-{{ checksum "player_app-checksum.txt" }}

      ## build player_app
      - run:
          working_directory: clients/player_app
          command: if [ ! -d "build" ]; then yarn build; fi

      ## store player_app cache
      - save_cache:
          key: player_app-{{ checksum "yarn.lock" }}-{{ checksum "app/graphql/schema.graphql" }}-{{ checksum "player_app-checksum.txt" }}
          paths:
            - clients/player_app/build


      # Assets
      ## generate checksum for assets
      - type: shell
        command: ./.circleci/assets_checksum.sh > assets-checksum.txt

      ## restore assets cache
      - restore_cache:
          key: assets-{{ checksum "Gemfile.lock" }}-{{ checksum "assets-checksum.txt" }}

      ## compile assets
      - run: bundle exec rake assets:precompile

      ## store assets cache
      - save_cache:
          key: assets-{{ checksum "Gemfile.lock" }}-{{ checksum "assets-checksum.txt" }}
          paths:
            - tmp/cache/assets


      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run tests
      - run: bundle exec rails test

      # Store Artifacts
      - store_artifacts:
          path: ~/project/tmp/coverage
          destination: coverage

      - store_artifacts:
          path: ~/project/tmp/perf
          destination: performance

      - store_artifacts:
          path: ~/project/tmp/capybara
          destination: capybara
