version: 2

jobs:
  build:
    working_directory: ~/ut

    docker:
      - image: circleci/ruby:2.5.0-node-browsers
      - image: circleci/postgres:9.4.12-alpine
      - image: redis:2.8.6

    environment:
      PGUSER: ubuntu
      RAILS_ENV: test
      RACK_ENV: test

    steps:
      # Checkout the source code
      - checkout
      - run: git submodule update --init

      # Restore bundle cache
      - type: cache-restore
        key: gemfile-{{ checksum "server/Gemfile.lock" }}

      # Bundle install dependencies
      - run: cd server && bundle install --with circleci --without production --without development --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: gemfile-{{ checksum "server/Gemfile.lock" }}
        paths:
          - server/vendor/bundle

      # Restore yarn cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}-{{ checksum "server/client/yarn.lock" }}

      # Yarn install dependencies
      - run: yarn install

      # Store yarn cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}-{{ checksum "server/client/yarn.lock" }}
          paths:
            - ./node_modules
            - ./server/client/node_modules
            - ./player-app/node_modules

      # Database setup
      - run: cd server && bundle exec rake db:create
      - run: cd server && bundle exec rake db:schema:load

      # Generate checksum for assets
      - type: shell
        command: |
          find server/app/assets/* -type f 2>/dev/null -exec md5sum {} \; > assets-checksum.txt

      # Restore assets cache
      - restore_cache:
          key: |
            assets
            {{ checksum "assets-checksum.txt" }}
            {{ checksum "server/Gemfile.lock" }}
            {{ checksum "server/client/yarn.lock" }}

      # Compile assets
      - run: cd server && bundle exec rake assets:precompile

      # Store assets cache
      - save_cache:
          key: |
            assets
            {{ checksum "assets-checksum.txt" }}
            {{ checksum "server/Gemfile.lock" }}
            {{ checksum "server/client/yarn.lock" }}
          paths:
            - server/public/assets
            - server/public/webpack
            - server/tmp/cache/assets

      # Generate checksum for player app
      - type: shell
        command: |
          git submodule status > player-app-checksum.txt

      # Restore player-app cache
      - restore_cache:
          key: player-app-{{ checksum "player-app-checksum.txt" }}

      # Build player-app
      - run: cd player-app && yarn build

      # Store player-app cache
      - save_cache:
          key: player-app-{{ checksum "player-app-checksum.txt" }}
          paths:
            - player-app/build

      # Run tests
      - run: cd server && bundle exec rake ci:all

      # Store Artifacts
      - store_artifacts:
          path: ~/ut/tmp/coverage
          destination: coverage

      - store_artifacts:
          path: ~/ut/tmp/capybara
          destination: capybara
