default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ut_dev

test:
  <<: *default
  database: ut_test
